language: generic
sudo: required
services:
  - dockerfile

before_install:
  - docker build -t gregmckenzie88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gregmckenzie88/docker-react npm run test
  # - docker run gregmckenzie88/docker-react npm run test -- --coverage
