language: generic
sudo: required
services:
  - dockerfile

before_install:
  - docker build -t gregmckenzie88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gregmckenzie88/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-689077909946'
  bucket_path: 'docker-react'
  on:
    branch: master
